import {isCurrent} from './session.mjs';
import {diffRows,compareProblems,strictInstant} from './rules.mjs';
import {COLUMNS} from './csv.mjs';
import {formatMoney} from './money.mjs';
import {messages} from '../i18n.js';
export const ASSUMPTIONS={currency:'CNY',unit:'one product / one unit',fee_base:'price minus merchant discount',fee_rounding:'half up to integer cents',excluded:['tax','returns','advertising','fixed costs'],scope:'Explicit operational constraints; independent row contribution; not platform approval, net profit, realized ROI or proof of authenticity.'};
export async function makeReport(session,lang='zh',at=new Date().toISOString()){
 if(!isCurrent(session))throw new Error('STALE_RESULTS');
 const snapshot=structuredClone(session);
 const bytes=new TextEncoder().encode(JSON.stringify({original:snapshot.original,draft:snapshot.draft}));
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');
 const report={schema_version:'promocheck-report-v1',language:lang,generated_at:at,rule_version:snapshot.draftResult.rule_version,revision:snapshot.revision,source:snapshot.source,input_fingerprint:{algorithm:'SHA-256',canonicalization:'UTF-8 JSON.stringify({original,draft}); array and property order preserved',value:hash},original:snapshot.original,draft:snapshot.draft,original_result:snapshot.originalResult,draft_result:snapshot.draftResult,changes:diffRows(snapshot.original,snapshot.draft),comparison:compareProblems(snapshot.originalResult,snapshot.draftResult),normalized_times:{original:snapshot.original.map(r=>({record_id:r.record_id,start_ms:strictInstant(r.start_at),end_ms:strictInstant(r.end_at)})),draft:snapshot.draft.map(r=>({record_id:r.record_id,start_ms:strictInstant(r.start_at),end_ms:strictInstant(r.end_at)}))},assumptions:ASSUMPTIONS,review:snapshot.review?.revision===snapshot.revision?snapshot.review:null};
 return report;
}
export function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function reportJSON(report){return JSON.stringify(report,null,2);}
export function reportHTML(report){
 const e=escapeHTML,t=messages[report.language]??messages.zh,zh=report.language==='zh';
 const table=rows=>`<div class="scroll"><table><thead><tr>${COLUMNS.map(k=>`<th>${e(t.fields[k])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${COLUMNS.map(k=>`<td>${e(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 const result=r=>`<ul>${r.problems.map(p=>`<li><b>${e(p.rule_id)} · ${e(p.severity)}</b> ${e(t.reasons[p.reason])} — ${e(p.record_ids.join(', '))} / ${e(p.fields.map(f=>t.fields[f]).join(', '))}${p.values?`<pre>${e(JSON.stringify(p.values))}</pre>`:''}</li>`).join('')||`<li>${e(t.clear)}</li>`}</ul><h3>${zh?'单品贡献（CNY / 件）':'Unit contribution (CNY / unit)'}</h3><ul>${r.contributions.map(c=>`<li>${e(c.record_id)}: ${c.contribution_cents===null?e(zh?'无法计算':'Cannot calculate'):e(formatMoney(c.contribution_cents))}${c.errors.length?' — '+e(c.errors.map(v=>`${t.fields[v.field]}: ${t.reasons[v.reason]}`).join('; ')):''}</li>`).join('')}</ul>`;
 return `<!doctype html><html lang="${zh?'zh-CN':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>PromoCheck ${zh?'复核报告':'Review report'}</title><style>body{font:14px/1.7 system-ui,sans-serif;max-width:1200px;margin:32px auto;padding:0 20px;color:#182439}h1,h2{color:#245ce0}table{border-collapse:collapse;font-size:12px}td,th{border:1px solid #ddd;padding:8px;text-align:left;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f7fa;padding:12px}.scroll{overflow:auto}.note{background:#fff6de;padding:16px}li{margin:8px 0}</style></head><body><h1>PromoCheck · ${zh?'复核报告':'Review report'}</h1><p>${e(report.generated_at)} · ${e(report.rule_version)} · ${zh?'修订':'Revision'} ${report.revision}</p><p>${zh?'来源':'Source'}: ${e(report.source.name)} · ${report.source.synthetic?(zh?'合成案例':'Synthetic example'):(zh?'用户输入，来源未验证':'User input, provenance unverified')}</p><p class="note">${zh?'单品贡献按每件独立方案计算，费用以优惠后收入为基数，四舍五入到分。不含税、退货、广告及固定成本，不是净利润或实际收益。配置检查不代表平台审核或推荐上线。':'Independent per-unit contribution; fees on net revenue rounded half up to cents. Excludes tax, returns, advertising and fixed costs. Not net profit, realized ROI, platform approval or launch advice.'}</p><h2>${zh?'人工复核':'Human review'}</h2>${report.review?`<p>${e(report.review.name)} · ${e(report.review.at)} · ${zh?'自声明，未认证身份':'Self-declared; identity not verified'}</p><pre>${e(report.review.note)}</pre>`:`<p>${zh?'未复核':'Not reviewed'}</p>`}<h2>${e(t.original)}</h2>${table(report.original)}${result(report.original_result)}<h2>${e(t.draft)}</h2>${table(report.draft)}${result(report.draft_result)}<h2>${e(t.comparison)}</h2><p>${e(t.resolved)} ${report.comparison.resolved.length} · ${e(t.remaining)} ${report.comparison.remaining.length} · ${e(t.introduced)} ${report.comparison.introduced.length}</p><ul>${report.changes.map(c=>`<li>${e(c.record_id)} / ${e(t.fields[c.field])}: ${e(c.before)} → ${e(c.after)}</li>`).join('')}</ul><p>SHA-256: ${e(report.input_fingerprint.value)}<br>${zh?'指纹仅标识输入内容，不验证来源或复核人身份。':'Fingerprint identifies input content only, not authenticity or reviewer identity.'}</p><details><summary>${zh?'完整结构化证据（含整数分及时间戳）':'Complete structured evidence (integer cents and timestamps)'}</summary><pre>${e(reportJSON(report))}</pre></details></body></html>`;
}
