import React from 'react';
import {formatMoney} from './core/money.mjs';
export default function Contribution({session,selected,current,t,lang}){
 const zh=lang==='zh';
 const before=session.originalResult?.contributions.find(c=>c.record_id===selected);
 const after=current?session.draftResult.contributions.find(c=>c.record_id===selected):null;
 const delta=before?.contribution_cents!=null&&after?.contribution_cents!=null?after.contribution_cents-before.contribution_cents:null;
 const activity=session.draft.find(r=>r.record_id===selected);
 function card(c,title){return <div><h3>{title}</h3>{!c?<p className="muted">{session.originalResult?t.stale:t.pending}</p>:c.contribution_cents===null?<div className="stale-note"><strong>{zh?'无法计算':'Cannot calculate'}</strong>{c.errors.map(e=><p key={`${e.field}-${e.reason}`}>{t.fields[e.field]}：{t.reasons[e.reason]}</p>)}</div>:<><p className={`money-total ${c.contribution_cents<0?'negative':''}`}>¥ {formatMoney(c.contribution_cents)}<small> / {zh?'件':'unit'}</small></p><p className="muted">{c.contribution_cents<0?(zh?'单品贡献为负，需人工处理':'Negative contribution — review required'):(zh?'不代表适合上线':'Not a launch recommendation')}</p><details><summary>{zh?'查看计算依据':'Calculation details'}</summary><dl>{[['price',c.inputs.price],['discount',c.inputs.discount],['net',c.net_cents],['cost',c.inputs.cost],['fulfillment',c.inputs.fulfillment],['fee',c.fee_cents]].map(([k,v])=><div key={k}><dt>{t.fields[k]??(k==='net'?(zh?'优惠后收入':'Net revenue'):(zh?'费用（按优惠后收入）':'Fee on net revenue'))}</dt><dd>¥ {formatMoney(v)}</dd></div>)}<div><dt>{t.fields.fee_percent}</dt><dd>{formatMoney(c.inputs.fee_percent)}%</dd></div></dl></details></>}</div>}
 return <section className="comparison contribution"><div className="section-heading"><div><h2>{zh?'单品贡献比较':'Unit contribution comparison'}</h2><p>{activity.activity_id} · CNY · {zh?'单商品、单件方案':'One product, one unit'}</p></div></div><p className="assumptions">{zh?'单品贡献 = 售价 − 商家优惠 − 商品成本 − 履约费用 − 费用。费用按优惠后收入计提，四舍五入到分。不含税、退货、广告及固定成本，不是净利润。':'Contribution = price − merchant discount − item cost − fulfillment − fee. Fee applies to net revenue, rounded half up to cents. Excludes tax, returns, advertising and fixed costs; not net profit.'}</p><div className="comparison-grid">{card(before,t.original)}{card(after,t.draft)}</div><p className="contribution-delta">{zh?'每件方案差额':'Difference per unit'}：{delta===null?'—':`${delta>0?'+':''}¥ ${formatMoney(delta)}`} · {zh?'按所填假设计算，不是已实现收益。存在排期冲突时，仅表示独立单行方案。':'Based on supplied assumptions, not realized gains. With scheduling conflicts, this is only an independent row calculation.'}</p></section>;
}
