import React,{useRef,useState} from 'react';
import {reviewSession} from './core/session.mjs';
import {makeReport,reportJSON,reportHTML} from './core/report.mjs';
export default function ReportPanel({session,setSession,current,lang}){
 const zh=lang==='zh'; const [name,setName]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[artifact,setArtifact]=useState(null),[busy,setBusy]=useState(false);
 const live=useRef({session,lang});live.current={session,lang};
 const validArtifact=artifact?.session===session&&artifact?.lang===lang?artifact:null;
 function review(e){e.preventDefault();try{setSession(s=>reviewSession(s,name,note));setError('');}catch{setError(zh?'先重新检查，复核人1–80字、意见1–1000字。':'Recheck first. Name: 1–80 characters; note: 1–1000.');}}
 async function prepare(){setBusy(true);setError('');try{const report=await makeReport(session,lang);if(live.current.session!==session||live.current.lang!==lang)return;setArtifact({session,lang,report});}catch{setError(zh?'报告生成失败，请重新检查后重试。':'Report generation failed. Recheck and try again.');}finally{setBusy(false);}}
 function download(format){if(!validArtifact||!current)return;try{const text=format==='html'?reportHTML(validArtifact.report):reportJSON(validArtifact.report);const url=URL.createObjectURL(new Blob([text],{type:format==='html'?'text/html;charset=utf-8':'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`promocheck-r${session.revision}.${format}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{setError(zh?'下载请求失败，可复制下方JSON保存。':'Download request failed. Copy the JSON below instead.');}}
 return <section className="comparison report-panel"><div className="section-heading"><div><h2>{zh?'复核与报告':'Review & report'}</h2><p>{zh?'可以带着未解决问题导出；报告保留原始证据。':'Unresolved issues may be exported; original evidence is retained.'}</p></div></div><div className="report-body"><p className="muted">{session.review?(zh?`已记录复核：${session.review.name}（自声明）`:`Review recorded: ${session.review.name} (self-declared)`):(zh?'未复核。修改配置或重新检查会撤销旧复核。':'Not reviewed. Editing or rechecking clears prior review.')}</p><form onSubmit={review}><label>{zh?'复核人（可选）':'Reviewer (optional)'}<input aria-label={zh?'复核人':'Reviewer'} value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>{zh?'复核意见':'Review note'}<textarea aria-label={zh?'复核意见':'Review note'} value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><button className="button secondary" disabled={!current||!name.trim()||!note.trim()}>{zh?'记录本次复核':'Record review'}</button></form><p>{!current?(zh?'当前草案未检查或已修改，请复查后生成报告。':'Recheck the current draft before generating a report.'):(zh?'报告包含全部输入，请自行决定分享范围；不会自动上传。':'Report includes all inputs. Choose sharing recipients yourself; nothing is uploaded.')}</p><button className="button primary" disabled={!current||busy} onClick={prepare}>{busy?(zh?'生成中…':'Generating…'):(zh?'生成当前报告':'Generate current report')}</button>{error&&<p role="alert">{error}</p>}{validArtifact&&<div className="report-ready"><p role="status">{zh?'报告已生成，HTML 与 JSON 来自同一份修订快照。点击下载后请检查浏览器下载列表；如果未保存，可复制下方 JSON。':'Report ready. HTML and JSON share one revision snapshot. Check browser downloads after clicking; if no file is saved, copy the JSON below.'}</p><div className="report-buttons"><button className="button secondary" onClick={()=>download('html')}>{zh?'下载 HTML 报告':'Download HTML report'}</button><button className="button secondary" onClick={()=>download('json')}>{zh?'下载 JSON 证据':'Download JSON evidence'}</button></div><details><summary>{zh?'查看 / 复制完整 JSON':'View / copy complete JSON'}</summary><textarea aria-label={zh?'报告 JSON':'Report JSON'} readOnly value={reportJSON(validArtifact.report)} rows={8} onFocus={e=>e.target.select()}/></details></div>}</div></section>;
}
